### ISSUE TITLE
Overridden @Test with @UseDataProvider is executed twice

### ISSUE THREAD

**Issue by nikowitt** [TNG/junit-dataprovider#87] opened 2017-02-16 08:20 UTC
Hi there,
```
public class Test {

@DataProvider
public static Object[][] test() {
  return $$($("test"));
}

@UseDataProvider
@Test
public void test(String dp) {
  //do something
}
```
and
```
public class AnotherTest extends Test{

@UseDataProvider
@Override
@Test
public void test(String dp) {
  //do something
}
```

When AnotherTest.test is executed, the test is executed twice. It seems that @UseDataProvider is recognized on both the overriden and the original method, therefore the runner assembles the test cases twice. I'm expecting the @UseDataProvider to be recognized on the overriden test only.

**Comment by aaschmid** [comment] 2017-02-16 10:08
Hi @nikowitt,

what is the behavior for a normal JUnit 5 test case without a special runner?

Cheers,
Andreas

**Comment by nikowitt** [comment] 2017-02-16 10:23
We're using JUnit 4 so I cannot say for JUNIT 5, but the default behaviour in JUNIT 4 without any special runner (thus stripping the params from the signature) is that only one test method (the @Overriden one) is executed.

**Comment by aaschmid** [comment] 2017-02-16 10:48
Ah ... sorry. I meant JUnit 4 ...
Ok so this is a defect and I need to fix it

**Comment by aaschmid** [comment] 2017-02-17 18:24
Hi @nikowitt,

sorry but I cannot reproduce it neither from Eclipse nor Gradle / Jenkins. Which JUnit4 version do you use? I used 4.12.

What do I do wrong? Test case is check in, see package `com.tngtech.test.java.junit.dataprovider.override` in `src/integTest/java`.

**Comment by nikowitt** [comment] 2017-02-20 06:30
Interesting, using this very simple test seems indeed to work. As we are using a Spring based dataprovider, the issue might be there. I will try to track this further down ASAP.

**Comment by aaschmid** [comment] 2017-10-03 20:26
Hi @nikowitt, 

any news on this?

Cheers,
Andreas

**Comment by nikowitt** [comment] 2017-10-06 04:32
Sorry, not yet (honestly, I forgot about this)... I will see what I can do in the near future.

**Comment by aaschmid** [comment] 2018-01-24 20:53
As I still cannot reproduce this issue and as I have no other idea where this defect could be located, I will close this for now. Please don't hesitate to reopen on new information.

**Closed by aaschmid** 2018-01-24 20:53 UTC
Labels: component: junit4, status: waiting external, type: defect
