### ISSUE TITLE
Can Gradle run these tests in parallel?

### ISSUE THREAD

**Issue by thejohnfreeman** [TNG/junit-dataprovider#92] opened 2017-02-18 20:08 UTC
Gradle cannot run JUnit `@Parameterized` tests in parallel, but TestNG has a `parallel` Boolean parameter on the `@DataProvider` annotation. Can Gradle run the junit-dataprovider tests in parallel?

**Comment by aaschmid** [comment] 2017-02-19 10:22
Hi @thejohnfreeman,

I have never tried this but in theory every junit-dataprovider test is a separate `FrameworkMethod`. This means if Gradle is parallelizing on this level, it should run out-of-the-box. I will try to reproduce this within the next days. Or is it somehow urgent?

Cheers,
Andreas

**Comment by thejohnfreeman** [comment] 2017-02-19 14:17
Not urgent. Thanks!

**Comment by gaponte1985** [comment] 2017-05-12 20:41
Any update about this issue?

**Comment by aaschmid** [comment] 2017-05-12 21:21
Hi @gaponte1985, thanks for the reminder. Currently my real spare time is a bit little but I will try to look at it as soon as possible ...

**Comment by gaponte1985** [comment] 2017-05-15 18:32
Thanks for the updated.

**Comment by gaponte1985** [comment] 2017-05-31 03:28
still working onm it?

**Comment by aaschmid** [comment] 2017-06-04 21:04
Hi @gaponte1985,

sorry for the long delay. I tried to parallelize the integration tests on junit-dataprovider itself using `test.maxParallelForks = 4` (see https://docs.gradle.org/3.0/dsl/org.gradle.api.tasks.testing.Test.html#org.gradle.api.tasks.testing.Test:maxParallelForks for details). And as I just use a normal runner as everybody else it should work. Also multiple threads are forked, though the tests are outputted in order ...

Can you try it and give feedback with a bigger test suite?

**Comment by gaponte1985** [comment] 2017-06-06 15:48
I dont get this one, can you please explain?

**Comment by aaschmid** [comment] 2017-06-06 16:09
Hi @gaponte1985,

I used https://github.com/TNG/junit-dataprovider/blob/master/build.gradle and added `test.maxParallelForks = 4` (see documentation on https://docs.gradle.org/3.0/dsl/org.gradle.api.tasks.testing.Test.html#org.gradle.api.tasks.testing.Test:maxParallelForks). 

Running `gradle build` using above changed `build.gradle` everything worked and tests are executed using multiple forked threads.

Can you try it and give feedback with your test suite?

**Comment by aaschmid** [comment] 2017-11-03 22:34
Hi @gaponte1985,
is this still an isssue or could you resolve it? 
Otherwise, how can I still help?
Cheers,
Andreas

**Comment by aaschmid** [comment] 2017-11-05 12:09
Hi @thejohnfreeman, 
looking at your issue now, you wanted to know if you can parallelize the dataprovider tests inherited from one single dataprovider for a single test method, right?
Cheers,
Andreas

**Comment by aaschmid** [comment] 2017-11-19 21:42
Closing this because of no further response from issue creator and other participants such that I cannot help any further.
Please don't hesitate to reopen and provide any further information or details.

**Closed by aaschmid** 2017-11-19 21:42 UTC
Labels: component: external, status: discussion, type: question
