### ISSUE TITLE
FrameworkMethod didn't get the right test

### ISSUE THREAD

**Issue by laaron2008** [TNG/junit-dataprovider#134] opened 2021-12-08 10:45 UTC
- ( ) **Bug report.** 
version: junit4-dataprovider 2.6

my test class likes this
![image](https://user-images.githubusercontent.com/23308615/145193999-23747c06-4f7d-4b0b-8e1e-80a22e19f9ac.png)

my dataprovider likes this
![image](https://user-images.githubusercontent.com/23308615/145194771-8c8ed250-0103-448f-b657-9bd0b11e6e8a.png)

when I run the getProduct case, the method is not getProduct, why?

**Comment by aaschmid** [comment] 2021-12-08 10:49
First guess: This is most likely due to the test names which are adjusted for working with data providers. What is the output of `method.getName()`?

**Comment by laaron2008** [comment] 2021-12-08 10:58
it's getDuplicationProductDetail

**Comment by aaschmid** [comment] 2021-12-08 11:04
Ok, understood. This is a problem because before we know which test cases are available, we need to execute the `dataProvider`. The result of the ´dataProvider` is however cached and therefore only called once in order to do not waste time. In your case with the wrong name :-(

Can you try switching the cache off using `@DataProvider(cache = false)` instead?

**Comment by laaron2008** [comment] 2021-12-08 11:09
I tried, but got the same result.
I just added the @DataProvider(cache = false)
Is there anything else I need to do?

**Comment by aaschmid** [comment] 2021-12-08 11:54
No, this should do the trick. The `dataProvider` method should now be called multiple times, once for each test method referencing it.

Then, I need some more time and try to get a reproducer for the issue.

**Comment by aaschmid** [comment] 2021-12-11 15:45
I am sorry @laaron2008 but I cannot reproduce it using `cache = false`. Here is my reproducer https://github.com/aaschmid/junit-dataprovider--134. Executed the tests from within IntelliJj or `./gradlew -i --no-build-cache clean test --tests "MyTest.getProduct[*0: {}, {}*]"` on command line.

**Comment by laaron2008** [comment] 2021-12-12 03:16
I changed https://github.com/aaschmid/junit-dataprovider--134, and reproduce the problem.
![image](https://user-images.githubusercontent.com/23308615/145698787-a6dfd570-afc0-44d4-a6bd-2fee1bf3febb.png)
![image](https://user-images.githubusercontent.com/23308615/145698790-e39d8104-b9be-4c02-a4d0-07d53fc36e4b.png)
when I run the getProduct case, the method.getName() printed getDuplicationProductDetail

**Comment by laaron2008** [comment] 2021-12-12 03:19
I guess the problem is 

> MyTest extends BaseJunit

**Comment by aaschmid** [comment] 2021-12-12 08:18
Even though I would not suggest adding the `@RunWith(DataProviderRunner.class)` on `BaseJunit` I cannot reproduce it (see updates on https://github.com/aaschmid/junit-dataprovider--134). What did I do forget?

<img width="701" alt="Bildschirmfoto 2021-12-12 um 09 15 52" src="https://user-images.githubusercontent.com/567653/145705400-f0d3299e-f240-4870-af76-fbcc6ebcc309.png">
<img width="765" alt="Bildschirmfoto 2021-12-12 um 09 15 57" src="https://user-images.githubusercontent.com/567653/145705401-e884d1c9-2e91-4af2-b678-4105877a3177.png">


Reason why I would not inherit from `BaseJunit`: because e.g. the IDE thinks you can execute it as tests which fails with `org.junit.runners.model.InvalidTestClassError: Invalid test class 'BaseJunit'` if there are not real test cases in there, e.g. if you run all test cases. And if there are testcases in, they will be executed with every child test class once...

**Comment by aaschmid** [comment] 2021-12-12 08:23
Same in IntelliJ
<img width="1349" alt="Bildschirmfoto 2021-12-12 um 09 22 59" src="https://user-images.githubusercontent.com/567653/145705535-0467c2bd-5824-4a20-a6e1-60e0d279f2ae.png">

**Comment by laaron2008** [comment] 2021-12-13 09:03
I gave up inherit and the case worked, thanks

**Comment by aaschmid** [comment] 2021-12-13 11:17
Ack, so I will close the issue. Don't hesitate to re-open it.

**Closed by aaschmid** 2021-12-13 11:17 UTC
